DROP TABLE BANK_ACCOUNT;

CREATE TABLE BANK_ACCOUNT 
(
  NAME VARCHAR(20) PRIMARY KEY
, PASSWORD VARCHAR(40) NOT NULL 
, BALANCE NUMBER NOT NULL 
, FUNMONEY NUMBER NOT NULL 
);

INSERT INTO BANK_ACCOUNT (name,PASSWORD,balance,funMoney) values('Tom','123',10000,0);
INSERT INTO BANK_ACCOUNT (name,PASSWORD,balance,funMoney) values('Casey','123',20000,0);
INSERT INTO BANK_ACCOUNT (name,PASSWORD,balance,funMoney) values('James','123',15000,0);

COMMIT;