SELECT * FROM (
  SELECT ROWNUM ROW_NUM, G.* FROM BEVERAGE_GOODS G
  WHERE¡@UPPER(GOODS_NAME) LIKE 'CA%'
  ORDER BY GOODS_ID
) WHERE ROW_NUM >= 4 AND¡@ROW_NUM¡@<= 6;


SELECT * FROM (
  SELECT ROWNUM ROW_NUM, G.* FROM BEVERAGE_GOODS G
  WHERE¡@UPPER(GOODS_NAME) LIKE 'CA%'
  ORDER BY GOODS_ID
) WHERE ROW_NUM BETWEEN 4 AND 6;