-- INNER JOIN 等值連接
SELECT G.GEOGRAPHY_ID, G.REGION_NAME, S.STORE_ID, S.STORE_NAME, S.GEOGRAPHY_ID
FROM GEOGRAPHY G , STORE_INFORMATION S
WHERE G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;

-- INNER JOIN 等值連接
-- 左區域、右商店
SELECT G.GEOGRAPHY_ID, G.REGION_NAME, S.STORE_ID, S.STORE_NAME, S.GEOGRAPHY_ID
FROM GEOGRAPHY G　INNER JOIN STORE_INFORMATION S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;


-- 列出全部的"區域"不論該區域底下是否有所屬商店
SELECT G.GEOGRAPHY_ID, G.REGION_NAME, S.STORE_ID, S.STORE_NAME, S.GEOGRAPHY_ID
FROM GEOGRAPHY G　LEFT JOIN STORE_INFORMATION S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;

SELECT G.GEOGRAPHY_ID, G.REGION_NAME, S.STORE_ID, S.STORE_NAME, S.GEOGRAPHY_ID
FROM GEOGRAPHY G , STORE_INFORMATION S
WHERE G.GEOGRAPHY_ID = S.GEOGRAPHY_ID(+);


SELECT G.GEOGRAPHY_ID, G.REGION_NAME, S.STORE_ID, S.STORE_NAME, S.GEOGRAPHY_ID
FROM GEOGRAPHY G　RIGHT JOIN STORE_INFORMATION S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;

SELECT G.GEOGRAPHY_ID, G.REGION_NAME, S.STORE_ID, S.STORE_NAME, S.GEOGRAPHY_ID
FROM GEOGRAPHY G , STORE_INFORMATION S
WHERE G.GEOGRAPHY_ID(+) = S.GEOGRAPHY_ID;


SELECT G.GEOGRAPHY_ID, G.REGION_NAME, S.STORE_ID, S.STORE_NAME, S.GEOGRAPHY_ID
FROM GEOGRAPHY G　FULL JOIN STORE_INFORMATION S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;


  SELECT G.GEOGRAPHY_ID, G.REGION_NAME, S.STORE_ID, S.STORE_NAME, S.GEOGRAPHY_ID
  FROM GEOGRAPHY G , STORE_INFORMATION S
  WHERE G.GEOGRAPHY_ID(+) = S.GEOGRAPHY_ID
  UNION
  SELECT G.GEOGRAPHY_ID, G.REGION_NAME, S.STORE_ID, S.STORE_NAME, S.GEOGRAPHY_ID
  FROM GEOGRAPHY G , STORE_INFORMATION S
  WHERE G.GEOGRAPHY_ID = S.GEOGRAPHY_ID(+);