SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'Steven' AND PHONE_NUMBER = '515.123.4567';

-- "SELECT * FROM EMPLOYEES WHERE FIRST_NAME = "+ firstName +" AND PHONE_NUMBER = " + phoneNumber;

-- 1 OR 1 = 1
SELECT * FROM EMPLOYEES WHERE FIRST_NAME = xxx AND PHONE_NUMBER = xxx;

SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 1 OR 1 = 1 AND PHONE_NUMBER = 1 OR 1 = 1;

SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 1 OR 1 = 1;

SELECT * FROM EMPLOYEES WHERE FIRST_NAME = '1 OR 1 = 1' AND PHONE_NUMBER = '1 OR 1 = 1';
