INSERT INTO BANK_ACCOUNT (NAME, PASSWORD, BALANCE, FUNMONEY) values('Wendy', 1234, 30000, 300.123);

-- 建議更新前先做查詢以確認要更新的資料範圍
SELECT * FROM BANK_ACCOUNT WHERE NAME = 'Wendy';

UPDATE BANK_ACCOUNT SET BALANCE = 888 WHERE NAME = 'Wendy';

ROLLBACK;